version: '2'
services:
  master:
    build: .
    container_name: giphy_jenkins
    volumes:
      - ./jenkins-master:/var/jenkins_home
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Xmx2048m

  worker:
    image: eeacms/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "admin"
      JENKINS_PASS: "giphy"
      JENKINS_RETRY: "10"
    volumes:
      - ./jenkins-slave:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-slave:
